# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/neeraj/Downloads/clion-2020.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/neeraj/Downloads/clion-2020.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neeraj/CLionProjects/SCoRe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neeraj/CLionProjects/SCoRe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/neeraj/Downloads/clion-2020.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/neeraj/Downloads/clion-2020.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neeraj/CLionProjects/SCoRe/CMakeFiles /home/neeraj/CLionProjects/SCoRe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neeraj/CLionProjects/SCoRe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named rtq_test

# Build rule for target.
rtq_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtq_test
.PHONY : rtq_test

# fast build rule for target.
rtq_test/fast:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/build
.PHONY : rtq_test/fast

#=============================================================================
# Target rules for targets named SCoRe

# Build rule for target.
SCoRe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SCoRe
.PHONY : SCoRe

# fast build rule for target.
SCoRe/fast:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/build
.PHONY : SCoRe/fast

#=============================================================================
# Target rules for targets named redis_test

# Build rule for target.
redis_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redis_test
.PHONY : redis_test

# fast build rule for target.
redis_test/fast:
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/build
.PHONY : redis_test/fast

#=============================================================================
# Target rules for targets named queue_test

# Build rule for target.
queue_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queue_test
.PHONY : queue_test

# fast build rule for target.
queue_test/fast:
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/build
.PHONY : queue_test/fast

#=============================================================================
# Target rules for targets named json_test

# Build rule for target.
json_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_test
.PHONY : json_test

# fast build rule for target.
json_test/fast:
	$(MAKE) -f CMakeFiles/json_test.dir/build.make CMakeFiles/json_test.dir/build
.PHONY : json_test/fast

#=============================================================================
# Target rules for targets named rtqn_test

# Build rule for target.
rtqn_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtqn_test
.PHONY : rtqn_test

# fast build rule for target.
rtqn_test/fast:
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/build
.PHONY : rtqn_test/fast

#=============================================================================
# Target rules for targets named score_server

# Build rule for target.
score_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 score_server
.PHONY : score_server

# fast build rule for target.
score_server/fast:
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/build
.PHONY : score_server/fast

#=============================================================================
# Target rules for targets named score

# Build rule for target.
score: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 score
.PHONY : score

# fast build rule for target.
score/fast:
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/build
.PHONY : score/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/daemonize.o: src/daemonize.cpp.o

.PHONY : src/daemonize.o

# target to build an object file
src/daemonize.cpp.o:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/daemonize.cpp.o
.PHONY : src/daemonize.cpp.o

src/daemonize.i: src/daemonize.cpp.i

.PHONY : src/daemonize.i

# target to preprocess a source file
src/daemonize.cpp.i:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/daemonize.cpp.i
.PHONY : src/daemonize.cpp.i

src/daemonize.s: src/daemonize.cpp.s

.PHONY : src/daemonize.s

# target to generate assembly for a file
src/daemonize.cpp.s:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/daemonize.cpp.s
.PHONY : src/daemonize.cpp.s

src/queue.o: src/queue.cpp.o

.PHONY : src/queue.o

# target to build an object file
src/queue.cpp.o:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/queue.cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue.cpp.o
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/src/queue.cpp.o
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/queue.cpp.o
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/queue.cpp.o
.PHONY : src/queue.cpp.o

src/queue.i: src/queue.cpp.i

.PHONY : src/queue.i

# target to preprocess a source file
src/queue.cpp.i:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/queue.cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue.cpp.i
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/src/queue.cpp.i
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/queue.cpp.i
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/queue.cpp.i
.PHONY : src/queue.cpp.i

src/queue.s: src/queue.cpp.s

.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.cpp.s:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/queue.cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue.cpp.s
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/src/queue.cpp.s
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/queue.cpp.s
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/queue.cpp.s
.PHONY : src/queue.cpp.s

src/queue_key.o: src/queue_key.cpp.o

.PHONY : src/queue_key.o

# target to build an object file
src/queue_key.cpp.o:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/queue_key.cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue_key.cpp.o
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/queue_key.cpp.o
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/queue_key.cpp.o
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/src/queue_key.cpp.o
.PHONY : src/queue_key.cpp.o

src/queue_key.i: src/queue_key.cpp.i

.PHONY : src/queue_key.i

# target to preprocess a source file
src/queue_key.cpp.i:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/queue_key.cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue_key.cpp.i
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/queue_key.cpp.i
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/queue_key.cpp.i
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/src/queue_key.cpp.i
.PHONY : src/queue_key.cpp.i

src/queue_key.s: src/queue_key.cpp.s

.PHONY : src/queue_key.s

# target to generate assembly for a file
src/queue_key.cpp.s:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/queue_key.cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue_key.cpp.s
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/queue_key.cpp.s
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/queue_key.cpp.s
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/src/queue_key.cpp.s
.PHONY : src/queue_key.cpp.s

src/queue_type.o: src/queue_type.cpp.o

.PHONY : src/queue_type.o

# target to build an object file
src/queue_type.cpp.o:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue_type.cpp.o
.PHONY : src/queue_type.cpp.o

src/queue_type.i: src/queue_type.cpp.i

.PHONY : src/queue_type.i

# target to preprocess a source file
src/queue_type.cpp.i:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue_type.cpp.i
.PHONY : src/queue_type.cpp.i

src/queue_type.s: src/queue_type.cpp.s

.PHONY : src/queue_type.s

# target to generate assembly for a file
src/queue_type.cpp.s:
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/queue_type.cpp.s
.PHONY : src/queue_type.cpp.s

src/redis.o: src/redis.cpp.o

.PHONY : src/redis.o

# target to build an object file
src/redis.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/redis.cpp.o
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/redis.cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/redis.cpp.o
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/src/redis.cpp.o
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/redis.cpp.o
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/redis.cpp.o
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/src/redis.cpp.o
.PHONY : src/redis.cpp.o

src/redis.i: src/redis.cpp.i

.PHONY : src/redis.i

# target to preprocess a source file
src/redis.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/redis.cpp.i
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/redis.cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/redis.cpp.i
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/src/redis.cpp.i
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/redis.cpp.i
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/redis.cpp.i
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/src/redis.cpp.i
.PHONY : src/redis.cpp.i

src/redis.s: src/redis.cpp.s

.PHONY : src/redis.s

# target to generate assembly for a file
src/redis.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/redis.cpp.s
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/src/redis.cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/redis.cpp.s
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/src/redis.cpp.s
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/src/redis.cpp.s
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/src/redis.cpp.s
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/src/redis.cpp.s
.PHONY : src/redis.cpp.s

src/reverse_trie_queue.o: src/reverse_trie_queue.cpp.o

.PHONY : src/reverse_trie_queue.o

# target to build an object file
src/reverse_trie_queue.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue.cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue.cpp.o
.PHONY : src/reverse_trie_queue.cpp.o

src/reverse_trie_queue.i: src/reverse_trie_queue.cpp.i

.PHONY : src/reverse_trie_queue.i

# target to preprocess a source file
src/reverse_trie_queue.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue.cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue.cpp.i
.PHONY : src/reverse_trie_queue.cpp.i

src/reverse_trie_queue.s: src/reverse_trie_queue.cpp.s

.PHONY : src/reverse_trie_queue.s

# target to generate assembly for a file
src/reverse_trie_queue.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue.cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue.cpp.s
.PHONY : src/reverse_trie_queue.cpp.s

src/reverse_trie_queue_node.o: src/reverse_trie_queue_node.cpp.o

.PHONY : src/reverse_trie_queue_node.o

# target to build an object file
src/reverse_trie_queue_node.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue_node.cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue_node.cpp.o
.PHONY : src/reverse_trie_queue_node.cpp.o

src/reverse_trie_queue_node.i: src/reverse_trie_queue_node.cpp.i

.PHONY : src/reverse_trie_queue_node.i

# target to preprocess a source file
src/reverse_trie_queue_node.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue_node.cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue_node.cpp.i
.PHONY : src/reverse_trie_queue_node.cpp.i

src/reverse_trie_queue_node.s: src/reverse_trie_queue_node.cpp.s

.PHONY : src/reverse_trie_queue_node.s

# target to generate assembly for a file
src/reverse_trie_queue_node.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue_node.cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue_node.cpp.s
.PHONY : src/reverse_trie_queue_node.cpp.s

src/reverse_trie_queue_node_key.o: src/reverse_trie_queue_node_key.cpp.o

.PHONY : src/reverse_trie_queue_node_key.o

# target to build an object file
src/reverse_trie_queue_node_key.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue_node_key.cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue_node_key.cpp.o
.PHONY : src/reverse_trie_queue_node_key.cpp.o

src/reverse_trie_queue_node_key.i: src/reverse_trie_queue_node_key.cpp.i

.PHONY : src/reverse_trie_queue_node_key.i

# target to preprocess a source file
src/reverse_trie_queue_node_key.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue_node_key.cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue_node_key.cpp.i
.PHONY : src/reverse_trie_queue_node_key.cpp.i

src/reverse_trie_queue_node_key.s: src/reverse_trie_queue_node_key.cpp.s

.PHONY : src/reverse_trie_queue_node_key.s

# target to generate assembly for a file
src/reverse_trie_queue_node_key.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/reverse_trie_queue_node_key.cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/reverse_trie_queue_node_key.cpp.s
.PHONY : src/reverse_trie_queue_node_key.cpp.s

src/s_queues..o: src/s_queues..cpp.o

.PHONY : src/s_queues..o

# target to build an object file
src/s_queues..cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/s_queues..cpp.o
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/s_queues..cpp.o
.PHONY : src/s_queues..cpp.o

src/s_queues..i: src/s_queues..cpp.i

.PHONY : src/s_queues..i

# target to preprocess a source file
src/s_queues..cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/s_queues..cpp.i
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/s_queues..cpp.i
.PHONY : src/s_queues..cpp.i

src/s_queues..s: src/s_queues..cpp.s

.PHONY : src/s_queues..s

# target to generate assembly for a file
src/s_queues..cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/s_queues..cpp.s
	$(MAKE) -f CMakeFiles/SCoRe.dir/build.make CMakeFiles/SCoRe.dir/src/s_queues..cpp.s
.PHONY : src/s_queues..cpp.s

tests/json_tester.o: tests/json_tester.cpp.o

.PHONY : tests/json_tester.o

# target to build an object file
tests/json_tester.cpp.o:
	$(MAKE) -f CMakeFiles/json_test.dir/build.make CMakeFiles/json_test.dir/tests/json_tester.cpp.o
.PHONY : tests/json_tester.cpp.o

tests/json_tester.i: tests/json_tester.cpp.i

.PHONY : tests/json_tester.i

# target to preprocess a source file
tests/json_tester.cpp.i:
	$(MAKE) -f CMakeFiles/json_test.dir/build.make CMakeFiles/json_test.dir/tests/json_tester.cpp.i
.PHONY : tests/json_tester.cpp.i

tests/json_tester.s: tests/json_tester.cpp.s

.PHONY : tests/json_tester.s

# target to generate assembly for a file
tests/json_tester.cpp.s:
	$(MAKE) -f CMakeFiles/json_test.dir/build.make CMakeFiles/json_test.dir/tests/json_tester.cpp.s
.PHONY : tests/json_tester.cpp.s

tests/queue_test.o: tests/queue_test.cpp.o

.PHONY : tests/queue_test.o

# target to build an object file
tests/queue_test.cpp.o:
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/tests/queue_test.cpp.o
.PHONY : tests/queue_test.cpp.o

tests/queue_test.i: tests/queue_test.cpp.i

.PHONY : tests/queue_test.i

# target to preprocess a source file
tests/queue_test.cpp.i:
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/tests/queue_test.cpp.i
.PHONY : tests/queue_test.cpp.i

tests/queue_test.s: tests/queue_test.cpp.s

.PHONY : tests/queue_test.s

# target to generate assembly for a file
tests/queue_test.cpp.s:
	$(MAKE) -f CMakeFiles/queue_test.dir/build.make CMakeFiles/queue_test.dir/tests/queue_test.cpp.s
.PHONY : tests/queue_test.cpp.s

tests/redis_test.o: tests/redis_test.cpp.o

.PHONY : tests/redis_test.o

# target to build an object file
tests/redis_test.cpp.o:
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/tests/redis_test.cpp.o
.PHONY : tests/redis_test.cpp.o

tests/redis_test.i: tests/redis_test.cpp.i

.PHONY : tests/redis_test.i

# target to preprocess a source file
tests/redis_test.cpp.i:
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/tests/redis_test.cpp.i
.PHONY : tests/redis_test.cpp.i

tests/redis_test.s: tests/redis_test.cpp.s

.PHONY : tests/redis_test.s

# target to generate assembly for a file
tests/redis_test.cpp.s:
	$(MAKE) -f CMakeFiles/redis_test.dir/build.make CMakeFiles/redis_test.dir/tests/redis_test.cpp.s
.PHONY : tests/redis_test.cpp.s

tests/reverse_trie_queue_test.o: tests/reverse_trie_queue_test.cpp.o

.PHONY : tests/reverse_trie_queue_test.o

# target to build an object file
tests/reverse_trie_queue_test.cpp.o:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/tests/reverse_trie_queue_test.cpp.o
.PHONY : tests/reverse_trie_queue_test.cpp.o

tests/reverse_trie_queue_test.i: tests/reverse_trie_queue_test.cpp.i

.PHONY : tests/reverse_trie_queue_test.i

# target to preprocess a source file
tests/reverse_trie_queue_test.cpp.i:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/tests/reverse_trie_queue_test.cpp.i
.PHONY : tests/reverse_trie_queue_test.cpp.i

tests/reverse_trie_queue_test.s: tests/reverse_trie_queue_test.cpp.s

.PHONY : tests/reverse_trie_queue_test.s

# target to generate assembly for a file
tests/reverse_trie_queue_test.cpp.s:
	$(MAKE) -f CMakeFiles/rtq_test.dir/build.make CMakeFiles/rtq_test.dir/tests/reverse_trie_queue_test.cpp.s
.PHONY : tests/reverse_trie_queue_test.cpp.s

tests/reverse_triequeue_node_test.o: tests/reverse_triequeue_node_test.cpp.o

.PHONY : tests/reverse_triequeue_node_test.o

# target to build an object file
tests/reverse_triequeue_node_test.cpp.o:
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/tests/reverse_triequeue_node_test.cpp.o
.PHONY : tests/reverse_triequeue_node_test.cpp.o

tests/reverse_triequeue_node_test.i: tests/reverse_triequeue_node_test.cpp.i

.PHONY : tests/reverse_triequeue_node_test.i

# target to preprocess a source file
tests/reverse_triequeue_node_test.cpp.i:
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/tests/reverse_triequeue_node_test.cpp.i
.PHONY : tests/reverse_triequeue_node_test.cpp.i

tests/reverse_triequeue_node_test.s: tests/reverse_triequeue_node_test.cpp.s

.PHONY : tests/reverse_triequeue_node_test.s

# target to generate assembly for a file
tests/reverse_triequeue_node_test.cpp.s:
	$(MAKE) -f CMakeFiles/rtqn_test.dir/build.make CMakeFiles/rtqn_test.dir/tests/reverse_triequeue_node_test.cpp.s
.PHONY : tests/reverse_triequeue_node_test.cpp.s

tests/score.o: tests/score.cpp.o

.PHONY : tests/score.o

# target to build an object file
tests/score.cpp.o:
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/tests/score.cpp.o
.PHONY : tests/score.cpp.o

tests/score.i: tests/score.cpp.i

.PHONY : tests/score.i

# target to preprocess a source file
tests/score.cpp.i:
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/tests/score.cpp.i
.PHONY : tests/score.cpp.i

tests/score.s: tests/score.cpp.s

.PHONY : tests/score.s

# target to generate assembly for a file
tests/score.cpp.s:
	$(MAKE) -f CMakeFiles/score.dir/build.make CMakeFiles/score.dir/tests/score.cpp.s
.PHONY : tests/score.cpp.s

tests/score_server.o: tests/score_server.cpp.o

.PHONY : tests/score_server.o

# target to build an object file
tests/score_server.cpp.o:
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/tests/score_server.cpp.o
.PHONY : tests/score_server.cpp.o

tests/score_server.i: tests/score_server.cpp.i

.PHONY : tests/score_server.i

# target to preprocess a source file
tests/score_server.cpp.i:
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/tests/score_server.cpp.i
.PHONY : tests/score_server.cpp.i

tests/score_server.s: tests/score_server.cpp.s

.PHONY : tests/score_server.s

# target to generate assembly for a file
tests/score_server.cpp.s:
	$(MAKE) -f CMakeFiles/score_server.dir/build.make CMakeFiles/score_server.dir/tests/score_server.cpp.s
.PHONY : tests/score_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... main"
	@echo "... rtq_test"
	@echo "... rebuild_cache"
	@echo "... SCoRe"
	@echo "... redis_test"
	@echo "... queue_test"
	@echo "... json_test"
	@echo "... rtqn_test"
	@echo "... score_server"
	@echo "... score"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/daemonize.o"
	@echo "... src/daemonize.i"
	@echo "... src/daemonize.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/queue_key.o"
	@echo "... src/queue_key.i"
	@echo "... src/queue_key.s"
	@echo "... src/queue_type.o"
	@echo "... src/queue_type.i"
	@echo "... src/queue_type.s"
	@echo "... src/redis.o"
	@echo "... src/redis.i"
	@echo "... src/redis.s"
	@echo "... src/reverse_trie_queue.o"
	@echo "... src/reverse_trie_queue.i"
	@echo "... src/reverse_trie_queue.s"
	@echo "... src/reverse_trie_queue_node.o"
	@echo "... src/reverse_trie_queue_node.i"
	@echo "... src/reverse_trie_queue_node.s"
	@echo "... src/reverse_trie_queue_node_key.o"
	@echo "... src/reverse_trie_queue_node_key.i"
	@echo "... src/reverse_trie_queue_node_key.s"
	@echo "... src/s_queues..o"
	@echo "... src/s_queues..i"
	@echo "... src/s_queues..s"
	@echo "... tests/json_tester.o"
	@echo "... tests/json_tester.i"
	@echo "... tests/json_tester.s"
	@echo "... tests/queue_test.o"
	@echo "... tests/queue_test.i"
	@echo "... tests/queue_test.s"
	@echo "... tests/redis_test.o"
	@echo "... tests/redis_test.i"
	@echo "... tests/redis_test.s"
	@echo "... tests/reverse_trie_queue_test.o"
	@echo "... tests/reverse_trie_queue_test.i"
	@echo "... tests/reverse_trie_queue_test.s"
	@echo "... tests/reverse_triequeue_node_test.o"
	@echo "... tests/reverse_triequeue_node_test.i"
	@echo "... tests/reverse_triequeue_node_test.s"
	@echo "... tests/score.o"
	@echo "... tests/score.i"
	@echo "... tests/score.s"
	@echo "... tests/score_server.o"
	@echo "... tests/score_server.i"
	@echo "... tests/score_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

